STR = { 	
	employee_name : ['Worker\'s Name','שם עובד'],
	type_buttons : [['Cleaning Workers','צו הרחבה בניקיון- חברות כח אדם'], ['Caregivers', 'עובדי סיעוד'], ['Hourly Workers', 'עובדים שעתיים'], ['Agricultural Workers','עובדי חקלאות'], ['Monthly Workers','עובדים בשכר חודשי'], ],
	caretaker_menu : ['Caregivers', 'עובדי סיעוד'],
	daily_worker_menu : ['Hourly Workers', 'עובדים שעתיים'],
	agricultural_worker_menu : ['Agricultural Workers','עובדי חקלאות'],
	monthly_worker_menu : ['Monthly Workers','עובדים בשכר חודשי'],
	start_date : ['Start Date ','תאריך התחלה'],
	end_date : ['End Date','תאריך סיום'],
	month : ['Month','חודש'],
	month_wage : ['Salary (NIS)','משכורת חודשית בשקלים'],
	daily_wage : ['Daily Wage (NIS)','שכר ליום בשקלים'],
	hourly_wage : ['Hourly Wage (NIS)','משכורת שעתית בשקלים'],
	week_allowance : ['Weekly Allowance (NIS)','דמי כיס שבועיים'],
	holidays_for_calc : ['Number of Holidays','ימי חג לחישוב'],
	calc_total_w_oldness : ['Consider Statue of Limitations','חישוב בהתחשב בהתיישנות'],
	//for_pension_calc : ['<b>For Pension Calculation</b>','<b>עבור חישוב פנסיה</b>'],
	num_days_in_week : ['Work Days per Week<br/>(Half for once every 2 weeks)','מספר ימים בשבוע<br/>(מחצית עבור פעם בשבועיים)'],
	num_hours_in_week : ['Work Hours per Week<br/>(half for once every 2 weeks)','מספר שעות שבועיות<br/>(מחצית עבור פעם בשבועיים)'],
	//date_example : ['Date format for example: 01/2008','דוגמא לתאריך בפורמט תקין: 01/2008'],	
	//first_month : ['First Month of Work','חודש תחילת העבודה'],	
	elig_compen : ['Eligiblilty for Separation Pay','זכאות לפיצויים'],
	show_elig_details : ['Show Separation Pay Calculation','פרוט חישוב הפיצויים'],
	recuper_day : ['Pay for Recuperation Day','תשלום ליום הבראה'],
	vacation_day : ['Pay for Vacation Day','תשלום ליום חופשה'],
	holiday_day : ['Pay for Holiday','תשלום ליום חג'],
	calc_recuper_vacation_and_holidays : ['Calculate Recuperation, Vacation, and Holiday Payments','חשב דמי הבראה, חופשה וחגים'],
	calc_compen : ['Calculate Pension, Separation Pay, and Prior Notice','חשב פנסיה, פיצויים והודעה מוקדמת'],
	alert_worker_type : ['Error: Type of worker hasn\'t been selected', 'שגיאה: לא נבחר סוג עובד'],
	alert_no_dates : ['Error: Please enter start and end date','שגיאה: הכנס תאריך התחלה וסוף'],
	alert_bad_days_in_week : ['Error: The number of days a week needs to be 1 to 6','שגיאה: מספר ימי עבודה בשבוע הוא בין 1-6'],
	alert_using_min_wage : ['Warning: The wage is below minimum, using minimum instead','אזהרה: המשכורת שהוכנסה היא מתחת למינימום, ולכן תוחלף במינימום'],
	alert_part_time_over_hundred : ['Error: percentage of work cannot exceed 100', 'שגיאה: אחוז המשרה אינו יכול להיות מעל 100'],
	output_recuper : ['Recuperation','חישוב דמי הבראה'],
	output_vacation : ['Vacation','חישוב חופשה'],
	output_early : ['Vacation','חישוב הודעה מוקדמת'],
	output_pension : ['Pension','חישוב פנסיה'],
	output_holidays: ['Holidays','חישוב חגים'],
	output_hishtalmut: ['Hishtalmut','חישוב השתלמות'],
	output_compen : ['Severance Pay','פיצויי פיטורין'],
	output_compen_complement : ['Full Severance Pay Complement','השלמה לפיצויי פיטורין מלאים'],
	output_compen_less_than_year : ['Worker has not worked a full year','לא הושלמה שנת עבודה'],
	output_compen_less_than_year_alert : ['Error: Uncheck eligilble for compensation, worker has not worked a full year','שגיאה: יש להוריד סימון זכאות לפיצויים, לא הושלמה שנת עבודה'],
	early_days : ['Prior Notice','תמורת הודעה מוקדמת'],
	compen_label1 : ['Wage X Number of Years','סכום השכר X מספר השנים'],
	compen_label2 : ['Calendar days','ימים קלנדריים'],
	compen_label3 : ['Work days','ימי עבודה'],
	compen_label4 : ['Amount to pay','סכום לתשלום'],
	compen_label5 : ['Wage X Number of Years + Overtime','סכום השכר X מספר השנים + שעות נוספות'],
	years : ['Years','שנים'],
	months : ['Months','חודשים'],
	period : ['Period','תקופה'],
	work_period : ['Work Period','תקופת עבודה'],
	days_potential : ['Days for Full Year', 'ימי זכאות'],
	days_net : ['Days for Worker', 'ימים לעובד'],
	vacation_days_potential : ['Potential Vacation Days', 'ימים לשנה מלאה'],
	vacation_days_net : ['Days for Worker', 'ימי חופשה לעובד'],
	amount_per_year : ['Amount', 'סכום בכל שנה'],
	total_amount : ['Total', 'סה"כ'],
	total_amount_oldness : ['Total (Statute of Limitations factored in)','סה"כ בהתחשב בהתיישנות'],
	total_amount_holidays : ['Salary for Holiday Work', 'שכר עבודה בימי החג'],
	alert_no_hours_in_week : ['Please enter the hours per week','הכנס שעות בשבוע'],
	work_percentage : ['Percentage of Work', 'אחוז משרה'],
	base_salary_for_calc : ['Base Salary for Calculation','שכר בסיס'],
	percentages : ['Percentage','אחוזים'],
	five_day_week : ['Five days a week? If not, six is assumed','האם אתה עובד 5 ימים בשבוע? אחרת נניח 6'],
	alert_date_not_available_for_pension : ['The work dates are not available for pension calculation','אין נתוני פנסיה עבור תקופת העבודה שהוכנסה'],
	num_months : ['Months for Pension','מס חודשים לחישוב'],
	subtotal : ['Subtotal','סכום ביניים'],
	subtotal_pension : ['Pension Portion','רכיב הגמל'],
	subtotal_separation : ['Separation Pay Portion','רכיב הפיצויים'],
	subtotal_period : ['Period Total','סכום תקופה'],
	subtotal_hishtalmut : ['Hishtalmut Pay Portion','רכיב השתלמות'],
	print : ['Print','הדפס'],
	reset : ['Reset','אתחל'],
	num_holidays : ['Number of holidays not yet used or payed','ימי חג שלא נוצלו או שולמו'],
	holidays : ['Holidays','חגים'],
	editor_name : ['Calculated By','שם עורך החישוב'],
	pension_statement : ['By law, the calculation is based on Israeli minimum wage or the actual wage - whichever is higher',' על פי חוק, החישוב נעשה על בסיס שכר המינימום בישראל או השכר בפועל - הגבוה מביניהם'],
	output_pension_expl : ['(employer allowance only, starting from 7th month at work)','(הפרשות המעסיק בלבד, החל מהחודש השביעי לעבודה)'],
	shekels : ['NIS','ש"ח'],
	employer_name : ['Employer Name','שם המעסיק'],
	comments : ['Comments','הערות'],
	cleaning_type : ['Type','סוג'],
	cleaning_private : ['Private','פרטי'],
	cleaning_public : ['Public','ציבורי'],
	cleaning_hotel : ['Hotel','מלון'],
	overtime : ['Overtime Hours <b>Post Reform<b>','שעות נוספות <b>מאז צו ההרחבה</b>'],
	transportationCosts : ['transportation Costs','הוצאות נסיעה'],
	overtime_pension : ['Pension for Overtime','פנסיה עבור שעות נוספות'],
	transportationCosts_pension : ['Pension for Transportation Costs','פנסיה עבור הוצאות נסיעה'],
	expansion_date_label : ['Expansion date:','תאריך צו ההרחבה:'],
}
//	 : ['',''],
