STR = { 	
	employee_name : ['Worker\'s Name','שם עובד','ชื่อคนงาน'],
	type_buttons : [['Cleaning Workers','צו הרחבה בניקיון- חברות כח אדם','พนักงานทำความสะอาด'], 
		['Caregivers', 'עובדי סיעוד','ผู้ดูแล'], 
		['Hourly Workers', 'עובדים שעתיים','พนักงานรายชั่วโมง'], 
		['Agricultural Workers','עובדי חקלאות','แรงงานเกษตร'], 
		['Monthly Workers','עובדים בשכר חודשי','ค่าแรงรายเดือน'], ],
	caretaker_menu : ['Caregivers', 'עובדי סיעוד' ,'ดูแลคนชรา'],
	daily_worker_menu : ['Hourly Workers', 'עובדים שעתיים','ค่าแรงต่อชม.'],
	agricultural_worker_menu : ['Agricultural Workers','עובדי חקלאות','แรงงานเกษตร'],
	monthly_worker_menu : ['Monthly Workers','עובדים בשכר חודשי','ค่าแรงรายเดือน'],
	start_date : ['Start Date ','תאריך התחלה','วันที่เริ่มทำงาน'],
	end_date : ['End Date','תאריך סיום','วันสุดท้ายที่ทำงาน'],
	month : ['Month','חודש','เดือน'],
	month_wage : ['Salary (NIS)','משכורת חודשית בשקלים','ค่าแรงรายเดือนเป็นเช็คเค่ล'],
	daily_wage : ['Daily Wage (NIS)','שכר ליום בשקלים','ค่าแรงรายวันเป็นเช็คเค่ล 8 ชม.'],
	hourly_wage : ['Hourly Wage (NIS)','משכורת שעתית בשקלים','ค่าแรงต่อชม.'],
	week_allowance : ['Weekly Allowance (NIS)','דמי כיס שבועיים','โบนัสประจำสัปดาห์'],
	holidays_for_calc : ['Number of Holidays','ימי חג לחישוב','จำนวนวันเทศกาลที่ได้รับ'],
	calc_total_w_oldness : ['Consider Statue of Limitations','חישוב בהתחשב בהתיישנות','xxไม่ต้องลง'],
	//for_pension_calc : ['<b>For Pension Calculation</b>','<b>עבור חישוב פנסיה</b>','เงินบำเน็จบำนาญ'],
	num_days_in_week : ['Work Days per Week<br/>(Half for once every 2 weeks)','מספר ימים בשבוע<br/>(מחצית עבור פעם בשבועיים)','จำนวนวันที่ทำงานต่ออาทิตย์'],
	num_hours_in_week : ['Work Hours per Week<br/>(half for once every 2 weeks)','מספר שעות שבועיות<br/>(מחצית עבור פעם בשבועיים)','จำนวนวันที่ทำงานต่ออาทิตย์'],
	//date_example : ['Date format for example: 01/2008','דוגמא לתאריך בפורמט תקין: 01/2008'],	
	//first_month : ['First Month of Work','חודש תחילת העבודה','เดือนที่เริ่มทำงาน'],	
	elig_compen : ['Eligiblilty for Separation Pay','זכאות לפיצויים','สิทธิที่จะได้รับเงินสิทธิ'],
	show_elig_details : ['Show Separation Pay Calculation','פרוט חישוב הפיצויים','รายละเอียดในการคิดเงินชดเชย'],
	recuper_day : ['Pay for Recuperation Day','תשלום ליום הבראה','ค่าพักฟื้นรายวัน'],
	vacation_day : ['Pay for Vacation Day','תשלום ליום חופשה','วันหยุดพักร้อนประจําปี'],
	holiday_day : ['Pay for Holiday','תשלום ליום חג','ค่าวันเทศกาล'],
	calc_recuper_vacation_and_holidays : ['Calculate Recuperation, Vacation, and Holiday Payments','חשב דמי הבראה, חופשה וחגים','การคิดเงินค่าพักฟื้น,วันหยุดพักร้อนประจําปีและวันเทศกาล'],
	calc_compen : ['Calculate Pension, Separation Pay, and Prior Notice','חשב פנסיה, פיצויים והודעה מוקדמת','เงินบำเน็จบำนาญ,ค่าชดเชย'],
	alert_worker_type : ['Error: Type of worker hasn\'t been selected', 'שגיאה: לא נבחר סוג עובד','ผิดพลาด ไม่ได้ระบุชนิดของแรงงาน'],
	alert_no_dates : ['Error: Please enter start and end date','שגיאה: הכנס תאריך התחלה וסוף','ผิดพลาด กรุณาระบุวันแรกและวันสุดท้ายที่ทำงาน'],
	alert_bad_days_in_week : ['Error: The number of days a week needs to be 1 to 6','שגיאה: מספר ימי עבודה בשבוע הוא בין 1-6','ผิดพลาด จำนวนวันที่ทำงานต่อสัปดาห์คือ1-6 '],
	alert_using_min_wage : ['Warning: The wage is below minimum, using minimum instead','אזהרה: המשכורת שהוכנסה היא מתחת למינימום, ולכן תוחלף במינימום','คำเตือน:จำนวนเงินเดือนต่ำกว่าขั้นต่ำ กรุณาระบุจำนวนเงินเดือนขึ้นต่ำ'],
	alert_part_time_over_hundred : ['Error: percentage of work cannot exceed 100', 'שגיאה: אחוז המשרה אינו יכול להיות מעל 100','ผิดพลาด เปอร์เซ็นต์ของงานไม่สามารถเกินกว่า 100'],
	output_recuper : ['Recuperation','חישוב דמי הבראה','การคิดค่าพักฟื้น'],
	output_vacation : ['Vacation Calculation','חישוב חופשה','วันหยุดพักร้อนประจําปี'],
	output_early : ['Early Notice Calculation','חישוב הודעה מוקדמת','การคิดค่าการแจ้งล่วงหน้า'],
	output_pension : ['Pension Calculation','חישוב פנסיה','การคิดเงินบําเน็จบํานาญ'],
	output_holidays: ['Holidays Calculation','חישוב חגים','การคิดค่าเทศกาล'],
	output_hishtalmut: ['Hishtalmut Calculation','חישוב השתלמות','การคิดค่าเงินสะสมการฝึกอบรม'],
	output_compen : ['Severance Pay','פיצויי פיטורין','เงินชดเชยในการไล่ออก หรือหมดสัญญา'],
	output_compen_complement : ['Full Severance Pay Complement','השלמה לפיצויי פיטורין מלאים','การคิดค่าบำเน็จบำนาญเพิ่มเติม'],
	output_compen_less_than_year : ['Worker has not worked a full year','לא הושלמה שנת עבודה','แรงงานทำงานต่ำกว่า 1 ปี'],
	output_compen_less_than_year_alert : ['Error: Uncheck eligilble for compensation, worker has not worked a full year','שגיאה: יש להוריד סימון זכאות לפיצויים, לא הושלמה שנת עבודה','ผิดพลาด จะต้องลดสิทธิในเงินชดเชยเพราะทำงานต่ำกว่าหนึ่งปี'],
	early_days : ['Prior Notice','תמורת הודעה מוקדמת','การแจ้งล่วงหน้าในการไล่ออก'],
	compen_label1 : ['Wage X Number of Years','סכום השכר X מספר השנים','จำนวนปีxจำนวนเงินเดือน'],
	compen_label2 : ['Calendar days','ימים קלנדריים','วันที่ตามปฎิทิน'],
	compen_label3 : ['Work days','ימי עבודה','วันที่ีทำงาน'],
	compen_label4 : ['Amount to pay','סכום לתשלום','จำนวนที่จ่าย'],
	compen_label5 : ['Wage X Number of Years + Overtime - Separation Pay Portion','סכום השכר X מספר השנים + שעות נוספות - רכיב הפיצויים','จำนวนปี+ค่าชม.โอที-ส่วนประกอบค่าชดเชยxจำนวนเงินเดือน,'],
	years : ['Years','שנים','ปี'],
	months : ['Months','חודשים','เดือน'],
	period : ['Period','תקופה','ช่วงระยะเวลา'],
	work_period : ['Work Period','תקופת עבודה','ระยะเวลางาน'],
	days_potential : ['Days for Full Year', 'ימי זכאות','วันที่มีสิทธิได้รับ'],
	days_net : ['Days for Worker', 'ימים לעובד','วันสำหรับแรงงาน'],
	vacation_days_potential : ['Potential Vacation Days', 'ימים לשנה מלאה','จำนวนวันต่อปีเต็ม'],
	vacation_days_net : ['Days for Worker', 'ימי חופשה לעובד','วันหยุดสำหรับคนงาน'],
	amount_per_year : ['Amount', 'סכום בכל שנה','จำนวนเงินต่อปี'],
	total_amount : ['Total', 'סה"כ','ทั้งหมด'],
	total_amount_oldness : ['Total (Statute of Limitations factored in)','סה"כ בהתחשב בהתיישנות'],
	total_amount_holidays : ['Salary for Holiday Work', 'שכר עבודה בימי החג','เงินเดือนสำหรับการทำงานในวันหยุด'],
	alert_no_hours_in_week : ['Please enter the hours per week','הכנס שעות בשבוע','จำนวนชั่วโมงต่อสัปดาห์'],
	work_percentage : ['Percentage of Work', 'אחוז משרה','เปอร์เซ็นต์การทำงาน'],
	base_salary_for_calc : ['Base Salary for Calculation','שכר בסיס','ฐานเงินเดือน'],
	percentages : ['Percentage','אחוזים','เปอร์เซ็นต์'],
	five_day_week : ['Five days a week? If not, six is assumed','האם אתה עובד 5 ימים בשבוע? אחרת נניח 6','ห้าวันทำการสัปดาห์'],
	alert_date_not_available_for_pension : ['The work dates are not available for pension calculation','אין נתוני פנסיה עבור תקופת העבודה שהוכנסה','วันที่ไม่มีเงินบำนาญ'],
	num_months : ['Months for Pension','מס חודשים לחישוב','จำนวนวันที่สำหรับการคำนวณ'],
	subtotal : ['Subtotal','סכום ביניים','ไม่ทั้งหมด'],
	subtotal_pension : ['Pension Portion','רכיב הגמל','บำเหน็จบำนาญรายย่อย'],
	subtotal_separation : ['Separation Pay Portion','רכיב הפיצויים','เงินชดเชย'],
	subtotal_period : ['Period Total','סכום תקופה','ช่วงยอดรวมย่อย'],
	subtotal_hishtalmut : ['Hishtalmut Pay Portion','רכיב השתלמות','ช่วงยอดรวมย่อย'],
	print : ['Print','הדפס','พิมพ์'],
	reset : ['Reset','אתחל','รีเซ็ต'],
	num_holidays : ['Number of holidays not yet used or payed','ימי חג שלא נוצלו או שולמו','จำนวนวันหยุดที่เป็น ไม่จ่ายเงิน'],
	holidays : ['Holidays','חגים','วันหยุด'],
	editor_name : ['Calculated By','שם עורך החישוב','ชื่อบรรณาธิการ'],
	pension_statement : ['By law, the calculation is based on Israeli minimum wage or the actual wage - whichever is higher',' על פי חוק, החישוב נעשה על בסיס שכר המינימום בישראל או השכר בפועל - הגבוה מביניהם','การคำนวณขึ้นอยู่กับค่าจ้างขั้นต่ำของอิสราเอลหรือค่าจ้างที่เกิดขึ้นจริง - แล้วแต่จำนวนใดจะสูงกว่า'],
	output_pension_expl : ['(employer allowance only, starting from 7th month at work)','(הפרשות המעסיק בלבד, החל מהחודש השביעי לעבודה)','(เบี้ยเลี้ยงนายจ้างเท่านั้นเริ่มต้นจากเดือนที่ 7 ในที่ทำงาน)'],
	shekels : ['NIS','ש"ח','เชคเคิล'],
	employer_name : ['Employer Name','שם המעסיק','ชื่อพนักงาน'],
	comments : ['Comments','הערות','แสดงความคิดเห็น'],
	cleaning_type : ['Type','סוג','ชนิด'],
	cleaning_private : ['Private','פרטי','เอกชน'],
	cleaning_public : ['Public','ציבורי','สาธารณะ'],
	cleaning_hotel : ['Hotel','מלון','โรงแรม'],
	overtime : ['Overtime Hours <b>Post Reform<b>','שעות נוספות <b>מאז צו ההרחבה</b>','ชั่วโมงทำงานล่วงเวลา <b>โพสต์การปฏิรูป</b>'],
	transportationCosts : ['transportation Costs','הוצאות נסיעה','ค่าใช้จ่ายในการขนส่ง'],
	overtime_pension : ['Pension for Overtime','פנסיה עבור שעות נוספות','เงินบำนาญสำหรับการทำงานล่วงเวลา'],
	transportationCosts_pension : ['Pension for Transportation Costs','פנסיה עבור הוצאות נסיעה','เงินบำนาญสำหรับค่าขนส่ง'],
	expansion_date_label : ['Expansion date:','תאריך צו ההרחבה:','วันที่ขยาย:'],
	output_lang : ['Output Language','שפת תצוגה','Output Language'],
};
//	 : ['',''],
donation_message = '<p>אנו מקווים שהשימוש במחשבון סייע לך במימוש זכויותייך.</br></br>על מנת שנוכל להמשיך בפעילותנו לקידום זכויות עובדים, אנו נשמח אם תירתם לסייע לנו במימון פעילות העמותה.  כל שקל שנתרם ל"קו לעובד" מכפיל עצמו פי 6!</br></br>תרומתך תאפשר לנו להמשיך בעשייה ובמאבק לחברה צודקת והוגנת יותר עבור כולנו</br></br><b>עמותת קו לעובד מוכרת כמוסד ציבורי לעניין תרומות (סעיף 46א).</b></br></br>לתרומה (קישור)</br></br>בברכה,</br></br>קו לעובד</p>';
