STR = { 	
	employee_name : ['Worker\'s Name','שם עובד'],
	caretaker_menu : ['Caregivers', 'עובדי סיעוד'],
	daily_worker_menu : ['Daily Workers', 'עובדים בשכר יומי'],
	agricultural_worker_menu : ['Agricultural Workers','עובדי חקלאות'],
	monthly_worker_menu : ['Monthly Workers','עובדים בשכר חודשי'],
	start_date : ['Start Date ','תאריך התחלה'],
	end_date : ['End Date','תאריך סיום'],
	month : ['Month','חודש'],
	month_wage : ['Salary (NIS)','משכורת חודשית בשקלים'],
	daily_wage : ['Daily Wage (NIS)','שכר ליום בשקלים'],
	week_allowance : ['Weekly Allowance (NIS)','דמי כיס שבועיים'],
	holidays_for_calc : ['Number of Holidays','ימי חג לחישוב'],
	calc_total_w_oldness : ['Consider Statue of Limitations','חישוב בהתחשב בהתיישנות'],
	//for_pension_calc : ['<b>For Pension Calculation</b>','<b>עבור חישוב פנסיה</b>'],
	num_days_in_week : ['Work Days per Week<br/>(Half for once every 2 weeks)','מספר ימים בשבוע<br/>(מחצית עבור פעם בשבועיים)'],
	num_hours_in_week : ['Work Hours per Week<br/>(half for once every 2 weeks)','מספר שעות שבועיות<br/>(מחצית עבור פעם בשבועיים)'],
	//date_example : ['Date format for example: 01/2008','דוגמא לתאריך בפורמט תקין: 01/2008'],	
	//first_month : ['First Month of Work','חודש תחילת העבודה'],	
	elig_compen : ['Eligiblilty for Separation Pay','זכאות לפיצויים'],
	show_elig_details : ['Show Separation Pay Calculation','פרוט חישוב הפיצויים'],
	recuper_day : ['Pay for Recuperation Day','תשלום ליום הבראה'],
	vacation_day : ['Pay for Vacation Day','תשלום ליום חופשה'],
	calc_recuper_vacation_and_holidays : ['Calculate Recuperation, Vacation, and Holiday Payments','חשב דמי הבראה, חופשה וחגים'],
	calc_compen : ['Calculate Pension, Separation Pay, and Prior Notice','חשב פנסיה, פיצויים והודעה מוקדמת'],
	alert_no_dates : ['Please enter start and end date','הכנס תאריך התחלה וסוף'],
	alert_bad_days_in_week : ['The number of days a week needs to be 1 to 6','מספר ימי עבודה בשבוע הוא בין 1-6'],
	alert_using_min_wage : ['The wage is below minimum, using minimum instead','המשכורת שהוכנסה היא מתחת למינימום, ולכן תוחלף במינימום'],
	output_recuper : ['Recuperation','חישוב דמי הבראה'],
	output_vacation : ['Vacation','חישוב חופשה'],
	output_pension : ['Pension','חישוב פנסיה'],
	output_holidays: ['Holidays','חישוב חגים'],
	output_compen : ['Severance Pay','פיצויי פיטורין'],
	output_compen_complement : ['Full Severance Pay Complement','השלמה לפיצויי פיטורין מלאים'],
	output_early : ['Prior Notice','תמורת הודעה מוקדמת'],
	compen_label1 : ['Wage X Number of Years','סכום השכר X מספר השנים'],
	compen_label1_2 : ['Wage X Number of Years - Separation Pay','סכום הפיצויים - (סכום השכר X מספר השנים)'],
	compen_label2 : ['Calendar days','ימים קלנדריים'],
	compen_label3 : ['Work days','ימי עבודה'],
	compen_label4 : ['Amount to pay','סכום לתשלום'],
	years : ['Years','שנים'],
	months : ['Months','חודשים'],
	period : ['Period','תקופה'],
	work_period : ['Work Period','תקופת עבודה'],
	days_potential : ['Days for Full Year', 'ימי זכאות'],
	days_net : ['Days for Worker', 'ימים לעובד'],
	vacation_days_potential : ['Potential Vacation Days', 'ימים לשנה מלאה'],
	vacation_days_net : ['Days for Worker', 'ימי חופשה לעובד'],
	amount_per_year : ['Amount', 'סכום בכל שנה'],
	total_amount : ['Total', 'סה"כ'],
	total_amount_oldness : ['Total (Statute of Limitations factored in)','סה"כ בהתחשב בהתיישנות'],
	total_amount_holidays : ['Total Amount', 'שכר עבודה בימי החג'],
	alert_no_hours_in_week : ['Please enter the hours per week','הכנס שעות בשבוע'],
	work_percentage : ['Percentage of Work', 'אחוז משרה'],
	base_salary_for_calc : ['Base Salary for Calculation','שכר בסיס לחישוב'],
	percentages : ['Percentage','אחוזים'],
	five_day_week : ['Five days a week? If not, six is assumed','האם אתה עובד 5 ימים בשבוע? אחרת נניח 6'],
	alert_date_not_available_for_pension : ['The work dates are not available for pension calculation','אין נתוני פנסיה עבור תקופת העבודה שהוכנסה'],
	num_months : ['Months for Pension','מספר חודשים לחישוב'],
	subtotal : ['Subtotal','סכום ביניים'],
	subtotal_pension : ['Pension Portion','רכיב הגמל'],
	subtotal_separation : ['Separation Pay Portion','רכיב הפיצויים'],
	subtotal_period : ['Period Total','סכום תקופה'],
	print : ['Print','הדפס'],
	reset : ['Reset','אתחל'],
	num_holidays : ['Days','מס\' חגים'],
	holidays : ['Holidays','חגים'],
	editor_name : ['Calculated By','שם עורך החישוב'],
	pension_statement : ['By law, the calculation is based on Israeli minimum wage or the actual wage - whichever is higher',' על פי חוק, החישוב נעשה על בסיס שכר המינימום בישראל או השכר בפועל - הגבוה מביניהם'],
	shekels : ['NIS','ש"ח'],
	employer_name : ['Employer Name','שם המעסיק'],
	comments : ['Comments','הערות'],
}
//	 : ['',''],
